SELECT PS_NO,PS_ID,PS_DD,MF_PSS.CUS_NO,CUS_NAME,OS_NO,BAT_NO,REM,BIL_TYPE
FROM
(
	       SELECT PS_NO,PS_ID,PS_DD,MF_PSS.CUS_NO,BIL_TYPE
             (SELECT TOP 1 NAME FROM CUST WHERE CUST.CUS_NO=MF_PSS.CUS_NO) AS CUS_NAME
            ,OS_NO,MF_PSS.BAT_NO,CONVERT(VARCHAR,MF_PSS.REM) AS REM
            ,TAX_ID,LZ_CLS_ID,CHK_MAN,TURN_ID,Zhang_ID,CUR_ID,KP_ID,YD_ID
          FROM MF_PSS
) AS MF_PSS